name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    name: TypeScript Type Checking
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build shared workspace
        run: npm run build:shared

      - name: Type check shared workspace
        run: npm run typecheck:shared

      - name: Type check server workspace
        run: npm run typecheck:server

      - name: Type check client workspace
        run: npm run typecheck:client

      - name: Type check entire monorepo
        run: npm run typecheck

  lint-test-build:
    runs-on: ubuntu-latest
    needs: typecheck
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Generate coverage report
        run: npm run test:coverage
        continue-on-error: true

      - name: Build projects
        run: npm run build

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            server/coverage/**
            client/coverage/**

      - name: Archive build artifacts
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: |
            shared/dist/**
            server/dist/**
            client/dist/**
